import type { CSSProperties } from "react";

type PrismTheme = Record<string, CSSProperties>;

// VS Code Dark+ inspired Prism theme
export const prismTheme: PrismTheme = {
  'code[class*="language-"]': {
    color: "#d4d4d4",
    background: "none",
    fontFamily:
      '"JetBrains Mono", Consolas, "Courier New", ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: "13px",
    lineHeight: "1.65",
    textShadow: "none",
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre",
    wordBreak: "normal",
    wordSpacing: "normal",
    tabSize: 4,
    hyphens: "none",
  },
  'pre[class*="language-"]': {
    color: "#d4d4d4",
    background: "none",
    margin: 0,
    padding: 0,
    overflow: "auto",
  },
  comment: { color: "#6a9955", fontStyle: "italic" },
  prolog: { color: "#6a9955" },
  doctype: { color: "#808080" },
  cdata: { color: "#808080" },
  punctuation: { color: "#d4d4d4" },
  property: { color: "#9cdcfe" },
  tag: { color: "#569cd6" },
  boolean: { color: "#569cd6" },
  number: { color: "#b5cea8" },
  constant: { color: "#4fc1ff" },
  symbol: { color: "#b5cea8" },
  deleted: { color: "#ce9178" },
  selector: { color: "#d7ba7d" },
  "attr-name": { color: "#9cdcfe" },
  string: { color: "#ce9178" },
  char: { color: "#ce9178" },
  builtin: { color: "#4ec9b0" },
  parameter: { color: "#9cdcfe" },
  inserted: { color: "#b5cea8" },
  operator: { color: "#d4d4d4" },
  entity: { color: "#569cd6" },
  url: { color: "#d7ba7d" },
  variable: { color: "#9cdcfe" },
  atrule: { color: "#dcdcaa" },
  "attr-value": { color: "#ce9178" },
  function: { color: "#dcdcaa", fontWeight: 500 },
  "class-name": { color: "#4ec9b0", fontWeight: 500 },
  keyword: { color: "#c586c0", fontWeight: 500 },
  regex: { color: "#d16969" },
  important: { color: "#569cd6", fontWeight: 700 },
  bold: { fontWeight: 700 },
  italic: { fontStyle: "italic" },
};
